---
# Prod values for spring-boot-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "prod"

replicaCount: 5

args:
  - "--spring.profiles.active=prod"

ingress:
  hosts:
    - host: spring-boot.local
      paths:
        - path: /api
          pathType: Prefix
          port: 8080
        - path: /logs
          pathType: Prefix
          port: 8081
        - path: /soap
          pathType: Prefix
          port: 8082
